apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
    - repoURL: 'https://gitlab.example.com/it-operations/k8s-config'
      path: 'argo-projects/kube-ray/charts/ray-cluster'
      targetRevision: master
      helm:
        valueFiles:
          - ap-values.yaml
    - repoURL: 'https://gitlab.example.com/it-operations/k8s-config'
      path: 'argo-projects/kube-ray/manifests/01-ray-cluster'
      targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuberay-projects
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true