affinity: {}
autoscaling:
  apiVersion: autoscaling/v2beta1
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
config:
  base_url: https://tika.movme.ru
fullnameOverride: "tika-server"
image:
  pullPolicy: IfNotPresent
  repository: apache/tika
  tag: 2.9.0.0
imagePullSecrets: []
ingress:
  className: external-ingress
  annotations:
    cert-manager.io/cluster-issuer: regru-letsencrypt-prod
#    cert-manager.io/cluster-issuer: inter-ca
    cert-manager.io/common-name: tika.movme.ru
#    cert-manager.io/duration: 8760h
    cert-manager.io/renew-before: 360h
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
  enabled: true
  hosts:
  - host: tika.movme.ru
    paths:
      - path: /
        pathType: Prefix
  tls:
    - hosts:
        - tika.movme.ru
      secretName: tika-https-cert

livenessProbe:
  failureThreshold: 20
  initialDelaySeconds: 15
  periodSeconds: 5
  scheme: HTTP
  timeoutSeconds: 30
nameOverride: ""
networkPolicy:
  allowExternal: false
  enabled: false
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
readinessProbe:
  failureThreshold: 20
  initialDelaySeconds: 15
  periodSeconds: 5
  scheme: HTTP
  timeoutSeconds: 30
replicaCount: 1
resources:
  limits:
    cpu: "4"
    memory: 2000Mi
  requests:
    cpu: "1"
    memory: 1500Mi
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 35002
  runAsNonRoot: true
  runAsUser: 35002
service:
  port: 9998
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: "tika-sa"
tolerations: []
