apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
  labels:
#    istio-injection: enabled
    security.deckhouse.io/pod-policy: privileged
#    security.deckhouse.io/pod-policy-action: warn