ARG RAY_IMAGE_VERSION=2.44.0-py310-cu124
FROM rayproject/ray:${RAY_IMAGE_VERSION}

ARG VLLM_VERSION
ARG HOME_DIR=/home/ray
WORKDIR ${HOME_DIR}

RUN sudo apt-get update && sudo apt-get install -y zip python3-pip
RUN sudo rm -rf /var/lib/apt/lists/*

# ── копируем код ────────────────────────────────────────────────
ADD serve.zip .

# ── Python‑зависимости без кеша ────────────────────────────────
RUN pip install --no-cache-dir --no-compile vllm==${VLLM_VERSION} \
 && pip install --no-cache-dir --no-compile httpx python-multipart PyJWT \
 && python -m pip cache purge \
 && sudo rm -rf /root/.cache /tmp/* /var/tmp/*

RUN pip freeze > requirements-new.txt