---
apiVersion: v1
kind: Secret
metadata:
  name: deepseek-cluster-auth-secret
  namespace: kuberay-projects
  annotations:
    kubernetes.io/service-account.name: sa-deepseek-cluster
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-deepseek-cluster
  namespace: kuberay-projects
secrets:
  - name: deepseek-cluster-auth-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deepseek-cluster:prometheus-access
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheuses/http"]
    resourceNames: ["main", "longterm"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deepseek-cluster:prometheus-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deepseek-cluster:prometheus-access
subjects:
  - kind: ServiceAccount
    name: sa-deepseek-cluster
    namespace: kuberay-projects
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deepseek-cluster:grafana-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:prometheus:grafana
subjects:
  - kind: ServiceAccount
    name: sa-deepseek-cluster
    namespace: kuberay-projects
